version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: taskcafe
      POSTGRES_USER: taskcafe
      POSTGRES_PASSWORD: taskcafe
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine

  taskcafe:
    build:
      context: .
      dockerfile: server/Dockerfile.server
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "postgres://taskcafe:taskcafe@postgres/taskcafe?sslmode=disable"
      REDIS_URL: "redis://redis:6379"
    depends_on:
      - postgres
      - redis

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.frontend
    ports:
      - "3333:3000"
    depends_on:
      - taskcafe

volumes:
  postgres_data:
